# Generated by Django 5.1.4 on 2024-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_post_user_subscription_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='feed.profile'),
        ),
    ]
