# Generated by Django 5.1.4 on 2024-12-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_profile_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='following', to='feed.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='feed.profile'),
        ),
    ]
