# Generated by Django 5.1.4 on 2025-01-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_remove_profile_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
